### ISSUE TITLE
Fantasy Calendar Integration

### ISSUE THREAD

**Issue by lazarusomega2000** [carlonicora/obsidian-rpg-manager#229] opened 2022-11-04 21:32 UTC
## Scope

I would like to use Fantasy Calendar for my date schemes within RPGM.

### Describe the solution you'd like

One way to do this would be to include the in game date in the YAML, but I don't know how it would work.
### Additional context
Right now I run a modern game in VtM so I am lucky to use the date manager out of the box, but I use other games that have alternate calendars for in game activities. Out of the Box, it doesn't seem that RPGM can handle that kind of thing yet.

**Comment by carlonicora** [comment] 2022-11-04 21:33
Duplicate of #125 being implemented for 3.2

**Closed by carlonicora** 2022-11-04 21:33 UTC
Labels: Feature
