### ISSUE TITLE
[BUG] Issue launching with FC when Vault is Indexing

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#244] opened 2022-11-16 17:42 UTC
## Scope

When Obsidian indexes the Vault, RPG Manager has trouble launching with FC Calendar.

### To Reproduce

With FC calendar installed and used in RPG Manager:
1. Do something to trigger **Vault Indexing** next time Obsidian starts. I'll be honest – I am not fully certain when and why Obsidian does this, but I think it's when I make a major like replacing an entire folder with a new version (which I might do to update my markdown files for D&D books and other compendiums).
2. When you launch and if Obsidian decides to Index your Vault, RPG Manager will not load until after the Indexing is complete and it throws a bunch of errors trying to work with Fantasy Calendar.
3. If you wait until Indexing finishes, it is able to proceed as normal and load as expected. RPG Manager will be unavailable until indexing finishes and the error can be alarming.

### Expected behaviour

If RPG Manager can't load during indexing due to FC Calendar, it should catch the error so the console doesn't scare the user. Whether RPG Manager can still load in during indexing or has to wait is probably dependent on the cause of the error. If it does have to wait, a message in the console to tell the user to wait might be nice (because if the user thinks something is broken and reboots Obsidian before it finishes, they will keep running into the Indexing issue on launch until they let it complete).

### Screenshots

![image](https://user-images.githubusercontent.com/18406537/202251720-aec76b6b-c462-43d4-863a-6b4bba1a2937.png)

### Desktop (please complete the following information)

 - OS: Ventura 13.0.1 
 -  Obsidian Version 1.0.3
 - RPG Manager Version 3.2.4
 - Fantasy Calendar Version 2.3.10

**Comment by carlonicora** [comment] 2022-11-18 13:29
Hi @cjolson 
Thanks for the report. I will try and reproduce the issue, but very well done for adding the screenshot of the error, it gives me food for thoughts!

**Comment by carlonicora** [comment] 2022-11-18 13:54
I was unable to reproduce the issue described; however, I have applied a patch to make avoid the triggering of the RPG Manager update at the same time as the FC calendar update.

@cjolson  When released, please do let me know if the issue is sorted. For the time being, I will keep this open

**Comment by carlonicora** [comment] 2022-11-18 14:49
@cjolson  can you please test on `3.2.5`?

**Comment by cjolson** [comment] 2022-11-18 19:20
@carlonicora, For sure. I will do an update now. Since I've only noticed it on Indexing, I'll see if I can trigger that – though I'll admit that I'm not sure how to do that most reliably. If I can't trigger it on purpose, I'll let you know what happens next time it does index.

**Comment by carlonicora** [comment] 2022-11-19 12:40
@cjolson I will close this for now, and we can reopen it if the issue persists

Thanks

**Closed by carlonicora** 2022-11-19 12:40 UTC
Labels: Bug

**Comment by cjolson** [comment] 2022-11-20 18:55
@carlonicora I did trigger it! It still throws some errors, but not nearly as many as before. My last Indexing was shorter, so it only threw once – but on a longer one it might throw half a dozen times (instead of the 850+ from before). 

<img width="441" alt="Screenshot 2022-11-20 at 1 53 11 PM" src="https://user-images.githubusercontent.com/18406537/202920459-4ff97ec3-53bf-47bc-bdd0-c96fe04d5530.png">
