### ISSUE TITLE
Installed RPG Manager and Dataview, but Command Panel shows nothing

### ISSUE THREAD

**Issue by namtrah** [carlonicora/obsidian-rpg-manager#38] opened 2022-09-13 17:32 UTC
Having an old vault where no plugins were installed, I installed RPG manager and Dataview, but I get this error
![image](https://user-images.githubusercontent.com/13903735/189970429-98c4537a-83de-4a62-b2e9-0f65856a7118.png)
And I see no commands in the command pallett

**Comment by namtrah** [comment] 2022-09-13 17:34
Additional Info:
Loading RpgManager 1.2.3
Dataview: version 0.5.46 (requires obsidian 0.13.11)

**Comment by carlonicora** [comment] 2022-09-13 17:35
Thanks for the report.
I will investigate and patch

**Comment by carlonicora** [comment] 2022-09-13 17:43
@namtrah The issue is in one of the tags, which must be misconfigured in your vault. Can you check your vault with `invalid metadata`? If you go in **View Mode** Obsidian will tell you if the metadata is correct or not.
When you find the incorrect metadata frontmatter, send them here so I can add the edge cases

**Comment by carlonicora** [comment] 2022-09-13 18:36
Fix released in [v1.2.5](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.2.5)

**Closed by carlonicora** 2022-09-13 18:36 UTC
Labels: bug
